### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by superosku** [fujiwara/Rin#21]
It seems that Dockerfile is not able to fully build the app. Instead it expectes there to be pre built binaries in `dist/` folder

**Comment by fujiwara** [comment]
I've been switched a build tool to goreleaser by a0f845badfb7a0c4c85db38dfb659c2aa5ecfed7, but `make images` were broken at the time.

Fixed by 198c50f277d8f7c0901d080c5da855235e99e8d7 and 0c00f13cf529d41da16ac994199c7218677be9bd
